#!/usr/bin/env python
#
# Main command to control ModelE
from __future__ import print_function

import os
srcdir = os.path.dirname(os.path.abspath(__file__))
import sys
sys.path.append(os.path.join(srcdir, '..', '..', 'python', 'lib'))

from modele import rundeck,rundir, pathutil

import string
import tempfile
import filecmp
import shutil

cmd_name = sys.argv[1]
argv = sys.argv[2:]

if cmd_name == 'setup':
    rundeck_fname = argv[0]
    run_dir = argv[1]

    rd=rundeck.load_rundeck(rundeck_fname)
    rundir.make_rundir(rd, run_dir)

elif cmd_name == 'run':
    run_dir = argv[1]

    modele_root = pathutil.modele_root()
    modelexe = os.path.join(modele_root, 'build', 'model', 'modelexe')
    print '(cd {}; mpirun -np 8 {} -cold-restart -i I)'.format(run_dir, modelexe)

else:
    sys.stderr.write('Unknown modele command: {}'.format(sys.argv))
