# Reads comments from the Fortran source file Constants_mod.F90
# Produces the Fortran source file ExportConstants.F90, which
# exports those constants from ModelE through a Fortran callback.
#
# by Elizabeth Fischer        April 26, 2014
from __future__ import print_function
import re
import netCDF4
import os.path
import sys
import string
try:
    import cf_units
    has_cf_units = True
except ImportError:
    has_cf_units = False


source_root = sys.argv[1]   # ${PROJECT_SOURCE_DIR}
build_root = sys.argv[2]        # ${PROJECT_BUILD_DIR}

#model_dir = os.path.realpath(os.path.join(os.path.dirname(__file__), '../../model'))

source_files = [ \
    ('shared/Constants_mod.F90', 'constant'), \
    ('SEAICE.f', 'seaice')]
#   ('LANDICE.f', 'landice')]

odir = os.path.join(build_root, 'model', 'landice')
export_constants_f90 = os.path.join(odir, 'ExportConstants.F90')

try: os.makedirs(odir)
except: pass


print('Writing %s' % export_constants_f90)

def split_comments(fin) :
    """Generator yields (line,comment) for each line"""
    for line in fin :
        pt = line.find('!')
        if pt < 0 : yield (line,None)
        yield (line[:pt], line[pt:])

paramRE = re.compile(r'!@param\s+(.*?)\s(.*?)\[\s*(.*?)\s*\]', re.IGNORECASE)

out = open(export_constants_f90, 'w')

# Get name of this script, strip off stuff above the ModelE source tree.
this_script = os.path.realpath(__file__)
exec_i = this_script.find('exec')
if exec_i >= 0 :
    this_script = this_script[exec_i:]

# ============================================================
out.write("""! This file is machine-generated.  DO NOT EDIT BY HAND!
! Generated by %s\n""" % this_script)

out.write("""module ExportConstants

abstract interface
    ! Callback used to communicate a constant out of ModelE
    subroutine set_constant_cb( &
        api, &
        name_f, name_len, &
        val, &
        units_f, units_len, &
        description_f, description_len) bind(c)
    use iso_c_binding
        type(c_ptr), value :: api
        character(c_char) :: name_f(*)
        integer(c_int), value :: name_len
        real(c_double), value :: val
        character(c_char) :: units_f(*)
        integer(c_int), value :: units_len
        character(c_char) :: description_f(*)
        integer(c_int), value :: description_len
    end subroutine
end interface

contains

! Communicate all ModelE constants to an external source
! @param set_constant Call this function on each ModelE constant.
subroutine set_all_constants(api, set_constant)
""")

for (leaf, module) in source_files :
    out.write("    use %s\n" % module)

out.write("""use iso_c_binding
implicit none
    type(c_ptr), value :: api
    procedure(set_constant_cb), pointer :: set_constant

""")
# ============================================================


defvars = []
for (leaf, module) in source_files :
    fname = os.path.join(source_root, 'model', leaf)
    print('Reading %s' % fname)
    for line,comment in split_comments(open(fname, 'r')) :
        # Parse the comment
        if comment is None : continue

        match = paramRE.match(comment)
        if match is not None :
            param_names = match.group(1)
            description = match.group(2).strip()
            units = match.group(3)

            # Error-check (validate) the unit
            if has_cf_units:
                try:
                    compiled_unit = cf_units.Unit(units)
                except ValueError:
                    print('Invalid unit on {0}: [{1}]'.format(param_names, units))

            fdescription = "'%s'" % description.replace("'", "''")

            for name in param_names.split(',') :
                name = name.lower()
                full_name = '%s::%s' % (module, name.lower())
                out.write(("    call set_constant(api, '%s', %d, %s, '%s', %d, &\n" + \
                    "        %s, %d)\n") \
                    % (full_name, len(full_name), name, units, len(units), fdescription, len(description)))

out.write("""end subroutine
end module
""")


out.close()
