set(giss_LSM_SOURCES
   ${CMAKE_CURRENT_SOURCE_DIR}/giss_LSM/GHY.f
   ${CMAKE_CURRENT_SOURCE_DIR}/giss_LSM/GHY_H.f
   ${CMAKE_CURRENT_SOURCE_DIR}/giss_LSM/SNOW_DRV.f
   ${CMAKE_CURRENT_SOURCE_DIR}/giss_LSM/SNOW.f
)


# Set sources and CPPFLAGS based on rundeck options
if (USE_ENT MATCHES "YES")
   set(giss_LSM_SOURCES ${giss_LSM_SOURCES} ${CMAKE_CURRENT_SOURCE_DIR}/giss_LSM/VEGETATION.f)
   #set(CPPFLAGS "${CPPFLAGS} -DUSE_ENT")  
endif()

if (OFFLINE_RUN MATCHES "YES")
   set(giss_LSM_SOURCES ${giss_LSM_SOURCES} ${CMAKE_CURRENT_SOURCE_DIR}/giss_LSM/VEGETATION.f)
   #set(CPPFLAGS "${CPPFLAGS} -DOFFLINE_RUN")  
endif()
