# Finds the OBSOLETE C++ interface to Pnetcdf
#
# Input Variables
#    PNETCDF_ROOT
# Produces:
#    PNETCDF_LIBRARY
#    PNETCDF_INCLUDE_DIR


FIND_PATH(PNETCDF_INCLUDE_DIR pnetcdf.h
	HINTS ${PNETCDF_ROOT}/include)

FIND_LIBRARY(PNETCDF_LIBRARY NAMES pnetcdf
	HINTS ${PNETCDF_ROOT}/lib ${PNETCDF_ROOT}/lib64)


IF (PNETCDF_INCLUDE_DIR AND PNETCDF_LIBRARY)
   SET(PNETCDF_FOUND TRUE)
ENDIF (PNETCDF_INCLUDE_DIR AND PNETCDF_LIBRARY)

IF (PNETCDF_FOUND)
   IF (NOT PNETCDF_FIND_QUIETLY)
      MESSAGE(STATUS "Found PNETCDF_LIBRARY: ${PNETCDF_LIBRARY}")
   ENDIF (NOT PNETCDF_FIND_QUIETLY)
ELSE (PNETCDF_FOUND)
   IF (PNETCDF_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find PNETCDF")
   ENDIF (PNETCDF_FIND_REQUIRED)
ENDIF (PNETCDF_FOUND)
