# Input Variables
#    FEXCEPTION_ROOT
# Produces:
#    FEXCEPTION_LIBRARY
#    FEXCEPTION_INCLUDE_DIR


FIND_PATH(FEXCEPTION_INCLUDE_DIR fexception_c.hpp
	HINTS ${FEXCEPTION_ROOT}/include)

FIND_LIBRARY(FEXCEPTION_LIBRARY NAMES fexception
	HINTS ${FEXCEPTION_ROOT}/lib)

IF (FEXCEPTION_INCLUDE_DIR AND FEXCEPTION_LIBRARY)
   SET(FEXCEPTION_FOUND TRUE)
ENDIF (FEXCEPTION_INCLUDE_DIR AND FEXCEPTION_LIBRARY)

IF (FEXCEPTION_FOUND)
   IF (NOT FEXCEPTION_FIND_QUIETLY)
      MESSAGE(STATUS "Found FEXCEPTION_LIBRARY: ${FEXCEPTION_LIBRARY}")
   ENDIF (NOT FEXCEPTION_FIND_QUIETLY)
ELSE (FEXCEPTION_FOUND)
   IF (FEXCEPTION_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find FEXCEPTION")
   ENDIF (FEXCEPTION_FIND_REQUIRED)
ENDIF (FEXCEPTION_FOUND)
